# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aritcle',
            name='tag',
            field=models.CharField(blank=True, choices=[('网站开发', '网站开发'), ('随笔、行记', '随笔、行记')], max_length=5, null=True),
        ),
    ]
