# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_aritcle_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('commend', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
