# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20170826_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
