# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_aritcle_hand_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aritcle',
            name='hand_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
