# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20171008_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aritcle',
            name='hand_img',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
